#nullable enable

using System;
using System.Collections.Generic;
using SaaSFoundry.EngineeringWorkbench.Core.Contracts.Agent;

namespace SaaSFoundry.EngineeringWorkbench.Execution.Blackboard;

/// <summary>
/// Immutable snapshot representation of the Mission Blackboard state at a specific point in time.
/// </summary>
/// <param name="Artifacts">Collection of static artifacts associated with the mission.</param>
/// <param name="GeneratedArtifacts">Collection of deliverables dynamically synthesized during execution.</param>
/// <param name="Evidence">Cryptographically auditable proof of execution and inspection.</param>
/// <param name="Diagnostics">Execution warnings, informational messages, and telemetry traces.</param>
/// <param name="ExecutionVariables">Key-value environmental execution parameters and flags.</param>
/// <param name="SharedMetadata">Metadata properties shared across participating agents.</param>
/// <param name="ExecutionOutputs">Key-value outputs generated by completed capabilities.</param>
/// <param name="ExecutionHistory">Chronological operational events and status transition log.</param>
/// <param name="ValidationEvidence">Validation diagnostics and verification test findings.</param>
/// <param name="EngineeringPackageReference">Identifier or digest of the associated Engineering Package.</param>
/// <param name="MissionPackageReference">Identifier or digest of the finalized Mission Package.</param>
/// <param name="AgentResults">Collection of structured execution outcomes reported by participating agents.</param>
public sealed record MissionBlackboardSnapshot(
    IReadOnlyList<string> Artifacts,
    IReadOnlyList<string> GeneratedArtifacts,
    IReadOnlyList<string> Evidence,
    IReadOnlyList<string> Diagnostics,
    IReadOnlyDictionary<string, string> ExecutionVariables,
    IReadOnlyDictionary<string, string> SharedMetadata,
    IReadOnlyDictionary<string, string> ExecutionOutputs,
    IReadOnlyList<string> ExecutionHistory,
    IReadOnlyList<string> ValidationEvidence,
    string? EngineeringPackageReference,
    string? MissionPackageReference,
    IReadOnlyList<AgentExecutionResult> AgentResults
);

/// <summary>
/// The canonical shared communication surface between agents during mission execution.
/// Agents never exchange information directly; all communication occurs via the Blackboard.
/// </summary>
public sealed class MissionBlackboard
{
    private readonly object _lock = new();
    private readonly List<string> _artifacts = new();
    private readonly List<string> _generatedArtifacts = new();
    private readonly List<string> _evidence = new();
    private readonly List<string> _diagnostics = new();
    private readonly Dictionary<string, string> _executionVariables = new(StringComparer.Ordinal);
    private readonly Dictionary<string, string> _sharedMetadata = new(StringComparer.Ordinal);
    private readonly Dictionary<string, string> _executionOutputs = new(StringComparer.Ordinal);
    private readonly List<string> _executionHistory = new();
    private readonly List<string> _validationEvidence = new();
    private readonly List<AgentExecutionResult> _agentResults = new();

    /// <summary>Gets the reference identifier for the associated Engineering Package.</summary>
    public string? EngineeringPackageReference { get; private set; }
    /// <summary>Gets the reference identifier for the finalized Mission Package.</summary>
    public string? MissionPackageReference { get; private set; }

    /// <summary>Registers an initial input or pre-existing artifact in the blackboard.</summary>
    public void AddArtifact(string artifact)
    {
        lock (_lock) { _artifacts.Add(artifact); }
    }

    /// <summary>Registers a newly generated deliverable artifact in the blackboard.</summary>
    public void AddGeneratedArtifact(string artifact)
    {
        lock (_lock) { _generatedArtifacts.Add(artifact); }
    }

    /// <summary>Appends execution audit evidence to the shared blackboard.</summary>
    public void AddEvidence(string evidence)
    {
        lock (_lock) { _evidence.Add(evidence); }
    }

    /// <summary>Appends operational diagnostic logs or telemetry traces.</summary>
    public void AddDiagnostic(string diagnostic)
    {
        lock (_lock) { _diagnostics.Add(diagnostic); }
    }

    /// <summary>Sets or overwrites a shared execution environment variable.</summary>
    public void SetVariable(string key, string value)
    {
        lock (_lock) { _executionVariables[key] = value; }
    }

    /// <summary>Sets or overwrites a shared operational metadata property.</summary>
    public void SetMetadata(string key, string value)
    {
        lock (_lock) { _sharedMetadata[key] = value; }
    }

    /// <summary>Sets or overwrites a named output parameter generated by an agent.</summary>
    public void SetOutput(string key, string value)
    {
        lock (_lock) { _executionOutputs[key] = value; }
    }

    /// <summary>Appends an entry to the chronological execution history log.</summary>
    public void AddHistoryEntry(string entry)
    {
        lock (_lock) { _executionHistory.Add(entry); }
    }

    /// <summary>Appends a verification finding to the validation evidence record.</summary>
    public void AddValidationEvidence(string evidence)
    {
        lock (_lock) { _validationEvidence.Add(evidence); }
    }

    /// <summary>Links an Engineering Package reference to the blackboard.</summary>
    public void SetEngineeringPackageReference(string reference)
    {
        lock (_lock) { EngineeringPackageReference = reference; }
    }

    /// <summary>Links a finalized Mission Package reference to the blackboard.</summary>
    public void SetMissionPackageReference(string reference)
    {
        lock (_lock) { MissionPackageReference = reference; }
    }

    /// <summary>Records the finished execution result reported by a participating agent.</summary>
    public void AddAgentResult(AgentExecutionResult result)
    {
        lock (_lock)
        {
            _agentResults.Add(result);
            foreach (var art in result.GeneratedArtifacts)
            {
                if (!_generatedArtifacts.Contains(art))
                {
                    _generatedArtifacts.Add(art);
                }
            }
        }
    }

    /// <summary>
    /// Creates a thread-safe, immutable snapshot of all current blackboard data and state.
    /// Uses allocation-efficient array conversions to avoid unnecessary wrapper object allocations.
    /// </summary>
    public MissionBlackboardSnapshot CreateSnapshot()
    {
        lock (_lock)
        {
            return new MissionBlackboardSnapshot(
                _artifacts.ToArray(),
                _generatedArtifacts.ToArray(),
                _evidence.ToArray(),
                _diagnostics.ToArray(),
                new Dictionary<string, string>(_executionVariables, StringComparer.Ordinal),
                new Dictionary<string, string>(_sharedMetadata, StringComparer.Ordinal),
                new Dictionary<string, string>(_executionOutputs, StringComparer.Ordinal),
                _executionHistory.ToArray(),
                _validationEvidence.ToArray(),
                EngineeringPackageReference,
                MissionPackageReference,
                _agentResults.ToArray()
            );
        }
    }
}
