<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\SaaSFoundry.EngineeringWorkbench.Core\SaaSFoundry.EngineeringWorkbench.Core.csproj" />
    <ProjectReference Include="..\SaaSFoundry.EngineeringWorkbench.Governance\SaaSFoundry.EngineeringWorkbench.Governance.csproj" />
    <ProjectReference Include="..\SaaSFoundry.EngineeringWorkbench.Infrastructure\SaaSFoundry.EngineeringWorkbench.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <NoWarn>$(NoWarn);IL2026;IL3050;IL2104</NoWarn>
  </PropertyGroup>

</Project>
