<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsAotCompatible>true</IsAotCompatible>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\SaaSFoundry.SDK.Import\SaaSFoundry.SDK.Import.csproj" />
    <ProjectReference Include="..\SaaSFoundry.SDK.AI\SaaSFoundry.SDK.AI.csproj" />
  </ItemGroup>
</Project>