using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using SaaSFoundry.EngineeringWorkbench.Builder.Models;

namespace SaaSFoundry.EngineeringWorkbench.Builder.Services;

public sealed class HostGenerator
{
    private readonly ArtifactWriter _artifactWriter;

    public HostGenerator(ArtifactWriter artifactWriter)
    {
        _artifactWriter = artifactWriter ?? throw new ArgumentNullException(nameof(artifactWriter));
    }

    public async Task GenerateAsync(CodeGenerationPlan plan, string targetRoot)
    {
        if (plan == null) throw new ArgumentNullException(nameof(plan));
        if (string.IsNullOrWhiteSpace(targetRoot)) throw new ArgumentException("Target root is required.", nameof(targetRoot));

        foreach (var cell in plan.Cells)
        {
            if (string.IsNullOrWhiteSpace(cell.CellId))
            {
                throw new InvalidOperationException("CellId is missing from CodeGenerationPlan.");
            }
            
            if (string.IsNullOrWhiteSpace(cell.TargetPath))
            {
                throw new InvalidOperationException($"TargetPath is missing for Cell '{cell.CellId}'.");
            }
            
            // Validate constraints before generating
            var uniqueRegistrations = new HashSet<string>();
            foreach (var reg in cell.Registrations)
            {
                if (string.IsNullOrWhiteSpace(reg.Namespace) && !string.IsNullOrWhiteSpace(reg.ExtensionMethod))
                    throw new InvalidOperationException($"Capability '{reg.CapabilityId}' in Cell '{cell.CellId}' has an extension method but an empty namespace.");

                
                if (!uniqueRegistrations.Add(reg.CapabilityId))
                    throw new InvalidOperationException($"Duplicate registration for capability '{reg.CapabilityId}' in Cell '{cell.CellId}'.");
            }

            // Ensure deterministic order
            var orderedRegistrations = cell.Registrations.OrderBy(r => r.RegistrationOrder).ThenBy(r => r.CapabilityId).ToList();

            var namespaces = orderedRegistrations.Where(r => !string.IsNullOrWhiteSpace(r.Namespace)).Select(r => r.Namespace).Distinct().OrderBy(n => n).ToList();

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine($"// Generated by SaaSFoundry.EngineeringWorkbench.Builder");
            sb.AppendLine($"// Product: {plan.ProductId}");
            sb.AppendLine($"// Cell: {cell.CellId}");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine();
            
            sb.AppendLine("using Microsoft.AspNetCore.Builder;");
            sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");

            foreach (var ns in namespaces)
            {
                sb.AppendLine($"using {ns};");
            }

            sb.AppendLine();
            sb.AppendLine("var builder = WebApplication.CreateBuilder(args);");
            sb.AppendLine();

            foreach (var reg in orderedRegistrations)
            {
                if (!string.IsNullOrWhiteSpace(reg.ExtensionMethod))
                {
                    sb.AppendLine($"builder.Services.{reg.ExtensionMethod}();");
                }
            }

            sb.AppendLine();
            sb.AppendLine("var app = builder.Build();");
            sb.AppendLine();
            
            sb.AppendLine("app.Run();");

            var cellRoot = Path.Combine(targetRoot, cell.TargetPath);
            var generatedDir = Path.Combine(cellRoot, "Generated");
            
            var outputPath = Path.Combine(generatedDir, "Program.cs");

            // Avoid path traversal issues
            var normalizedRoot = Path.GetFullPath(targetRoot);
            var normalizedOutput = Path.GetFullPath(outputPath);
            
            if (!normalizedOutput.StartsWith(normalizedRoot))
            {
                throw new InvalidOperationException("Generated path escapes target root.");
            }

            // Verify the path is inside 'Generated' folder
            var parentDir = Path.GetFileName(Path.GetDirectoryName(normalizedOutput));
            if (!string.Equals(parentDir, "Generated", StringComparison.OrdinalIgnoreCase))
            {
                throw new InvalidOperationException("Target path must be inside a 'Generated' directory.");
            }

            await _artifactWriter.WriteAsync(outputPath, sb.ToString());
        }
    }
}
