using System;
using System.Collections.Generic;
using System.IO;
using System.Text.Json;
using System.Threading.Tasks;
using SaaSFoundry.EngineeringWorkbench.Core.Contracts.Packaging;
using SaaSFoundry.EngineeringWorkbench.Core.Contracts.Validation;

namespace SaaSFoundry.EngineeringWorkbench.Packaging;

public sealed class PackagingEngine : IPackagingEngine
{
    public EngineeringPackage CreatePackage(string packageId, ValidationReport report, IReadOnlyList<string> artifacts)
    {
        return new EngineeringPackage(packageId, report, artifacts);
    }

    public Task ExportPackageAsync(EngineeringPackage package, IPackageExporter exporter, string destinationPath)
    {
        return exporter.ExportAsync(package, destinationPath);
    }
}

public sealed class FolderPackageExporter : IPackageExporter
{
    public string ExporterName => "FolderExporter";

    public async Task ExportAsync(EngineeringPackage package, string destinationPath)
    {
        System.Console.WriteLine($"  [Packaging] Exporting Engineering Package '{package.PackageId}' to '{destinationPath}' via {ExporterName}");
        
        Directory.CreateDirectory(destinationPath);

        // 1. Write the artifacts (Capabilities provide the logical paths/names)
        foreach (var artifact in package.ArtifactPaths)
        {
            var targetPath = Path.Combine(destinationPath, artifact);
            var targetDir = Path.GetDirectoryName(targetPath);
            if (!string.IsNullOrEmpty(targetDir))
            {
                Directory.CreateDirectory(targetDir);
            }
            // Placeholder content for the artifact
            await File.WriteAllTextAsync(targetPath, $"# Generated Artifact: {artifact}\n\nGenerated by SaaSFoundry Engineering Workbench v1.0");
        }

        // 2. Write validation-report.json
        var reportJson = JsonSerializer.Serialize(package.Report, new JsonSerializerOptions { WriteIndented = true });
        await File.WriteAllTextAsync(Path.Combine(destinationPath, "validation-report.json"), reportJson);

        // 3. Write package-manifest.json
        var manifest = new
        {
            PackageId = package.PackageId,
            WorkbenchVersion = "1.0.0",
            GeneratedUtc = DateTimeOffset.UtcNow,
            Artifacts = package.ArtifactPaths,
            ValidationReport = package.Report,
            ChecksumPlaceholder = "SHA256:00000000000000000000000000000000",
            Exporter = ExporterName
        };
        var manifestJson = JsonSerializer.Serialize(manifest, new JsonSerializerOptions { WriteIndented = true });
        await File.WriteAllTextAsync(Path.Combine(destinationPath, "package-manifest.json"), manifestJson);

        System.Console.WriteLine($"  [Packaging] Successfully exported {package.ArtifactPaths.Count} artifacts, validation report, and manifest.");
    }
}
